### ISSUE TITLE
Item returning code can crash if the quiver runs out due to erosion

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#2074]
```
Core was generated by `/notdnethack-2022.09.18/notdnethack -u Demo'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f1a0f8ff859 in __GI_abort () at abort.c:79
#2  0x00007f1a0f96a26e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f1a0fa94298 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f1a0f9722fc in malloc_printerr (str=str@entry=0x7f1a0fa965d0 "free(): double free detected in tcache 2")
    at malloc.c:5347
#4  0x00007f1a0f973f6d in _int_free (av=0x7f1a0fac9b80 <main_arena>, p=0x55d75f069fc0, have_lock=0) at malloc.c:4201
#5  0x000055d75e3750be in dealloc_obj (obj=0x55d75f069fd0) at src/mkobj.c:3572
#6  0x000055d75e620cae in obfree (obj=0x55d75f069fd0, merge=0x7fff4a9c98f0) at src/shk.c:1090
#7  0x000055d75e232c1d in merged (potmp=0x7fff4a9c9da8, pobj=0x7fff4a9c9d98) at src/invent.c:238
#8  0x000055d75e233189 in addinv (obj=0x55d75f069fd0) at src/invent.c:406
#9  0x000055d75e5bcd02 in return_thrownobj (magr=0x55d75eaed320 <youmonst>, thrownobj=0x55d75f069fd0)
    at src/projectile.c:1683
#10 0x000055d75e5aea45 in projectile (magr=0x55d75eaed320 <youmonst>, ammo=0x55d75f069fd0, vpointer=0x55d75f08b560,
    hmoncode=12, initx=18, inity=17, dx=1, dy=0, dz=0, initrange=13, forcedestroy=0 '\000', verbose=1 '\001',
    impaired=0 '\000') at src/projectile.c:554
#11 0x000055d75e5c2499 in uthrow (ammo=0x55d75f069fd0, launcher=0x55d75f08b560, shotlimit=0, forcedestroy=0 '\000')
    at src/projectile.c:2596
#12 0x000055d75e5bf7a3 in dofire () at src/projectile.c:2145
#13 0x000055d75e0c496b in rhack (cmd=0x55d75eae75a0 <in_line> "f") at src/cmd.c:3240
#14 0x000055d75dfc6c86 in moveloop () at src/allmain.c:3196
#15 0x000055d75e93192c in main (argc=3, argv=0x7fff4a9ca338) at sys/unix/unixmain.c:296
(gdb)
```
This happened to me in ndnh but it's definitely a dnh bug. I was shooting water elementals with multishot loyal returning green-steel arrows. I believe this happened when the quiver ran out due to different erosion levels of the arrows affecting stacking.

**Comment by NeroOneTrueKing** [comment]
Can reproduce in dnh.

**Comment by NeroOneTrueKing** [comment]
Steps to reproduce:
Have 2 (stacking) returning arrows.
Get 1 rusty.
Multishot the other at a water elemental.

The multishot code is _not okay_ with the ammo disappearing during multishot.
Usually, it's safe because it will only multishot up to the carried quantity... unless your ammo is returning, in which case I'm not sure how asan hasn't been screaming about this already.
