### ISSUE TITLE
Slipped Annulus can result in seg fault

### ISSUE THREAD

**Issue by baoliejuan** [Chris-plus-alphanumericgibberish/dNAO#2232]
How to recreate:
1.grease your Annulus
2.throw the Annulus
When the Annulus slips, there is a chance to receive the seg fault, despite what form Annulus is and what direction you throw.

**Comment by RikerW** [comment]
```
#0  0x0000555555f7b7a0 in hmoncore (magr=0x55555623e580 <youmonst>, mdef=0x55555623e580 <youmonst>, attk=0x0, originalattk=0x0, weapon_p=0x7fffffffd7f0, 
    vpointer=0x0, hmoncode=12, flatbasedmg=0, monsdmg=0, dohitmsg=1 '\001', dieroll=0, recursed=0 '\000', vis=7) at src/xhity.c:15198
#1  0x0000555555f697fd in hmon_general (magr=0x55555623e580 <youmonst>, mdef=0x55555623e580 <youmonst>, attk=0x0, originalattk=0x0, 
    weapon_p=0x7fffffffd7f0, vpointer=0x0, hmoncode=12, flatbasedmg=0, monsdmg=0, dohitmsg=1 '\001', dieroll=0, recursed=0 '\000', vis=-1)
    at src/xhity.c:12977
#2  0x0000555555c96b04 in projectile (magr=0x55555623e580 <youmonst>, ammo=0x555556385840, vpointer=0x0, hmoncode=4, initx=28, inity=15, dx=1, dy=0, dz=0, 
    initrange=10, forcedestroy=0 '\000', verbose=1 '\001', impaired=1 '\001') at src/projectile.c:577
#3  0x0000555555cab4ac in uthrow (ammo=0x555556385840, launcher=0x0, shotlimit=0, forcedestroy=0 '\000') at src/projectile.c:2723
#4  0x0000555555ca8e61 in dofire () at src/projectile.c:2361
#5  0x000055555570e881 in rhack (cmd=0x55555622bec0 <in_line> "f") at src/cmd.c:3606
#6  0x00005555555e47c3 in moveloop () at src/allmain.c:3286
#7  0x000055555605aef9 in main (argc=4, argv=0x7fffffffdca8) at sys/unix/unixmain.c:296
```

backtrace

line at fault `src/xhity.c:15198`
```
dr = (youdef ? roll_udr(magr, attk->aatyp) : roll_mdr(mdef, magr, attk->aatyp));
```
seems like a null attack struct and the game doesn't like trying to figure out what kind that was
